version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env  # <- Ensure this path is correct
    depends_on:
      - db

  db:
    build: db
    ports:
      - "6739:6739"
    volumes:
      - ./data:/data

